apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: postgres-mcp-server-binary
  namespace: mcp-server
spec:
  output:
    to:
      kind: ImageStreamTag
      name: postgres-mcp-server:latest
  source:
    type: Binary
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  triggers:
    - type: ConfigChange
  runPolicy: Serial 